# Generated by Django 6.0.6 on 2026-09-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('bitpay', 'بیت\u200cپی')], default='zarinpal', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
