# Generated by Django 6.0.5 on 2026-06-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='متن آهنگ'),
        ),
    ]
