# Generated by Django 6.0.5 on 2026-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
