# Generated by Django 6.0.5 on 2026-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_track_number_music_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='is_vip',
            field=models.BooleanField(default=True),
        ),
    ]
