# Generated by Django 6.0.5 on 2026-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
    ]
