# Generated by Django 6.0.5 on 2026-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_artist_slug_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
