# Generated by Django 6.0.6 on 2026-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_artist_slug_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
    ]
