# Generated by Django 6.0.6 on 2026-06-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_artist_slug_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='zip_file',
        ),
        migrations.RemoveField(
            model_name='music',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='music',
            name='track_number',
        ),
        migrations.RemoveField(
            model_name='music',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='music',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre'),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
