# Generated by Django 6.0.6 on 2026-06-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_album_zip_file_remove_music_title_en_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together=set(),
        ),
    ]
