# Generated by Django 6.0.6 on 2026-06-21 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_commentreport_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name_en',
        ),
        migrations.AddField(
            model_name='album',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='albums_zip/'),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='music',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_vip',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='متن آهنگ'),
        ),
        migrations.AlterField(
            model_name='music',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together={('comment', 'user')},
        ),
    ]
