# Generated by Django 6.0.6 on 2026-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_genre_name_en_album_zip_file_genre_slug_en_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='album',
            name='zip_file',
        ),
        migrations.RemoveField(
            model_name='music',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='music',
            name='track_number',
        ),
        migrations.RemoveField(
            model_name='music',
            name='year',
        ),
        migrations.AlterField(
            model_name='album',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
