# Generated by Django 6.0.6 on 2026-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_alter_commentreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
