# Generated by Django 6.0.6 on 2026-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_album_slug_en_alter_artist_slug_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name_fa',
            field=models.CharField(blank=True, help_text='نام فارسی آرتیست (خودکار پر می\u200cشود)', max_length=200, null=True),
        ),
    ]
