# Generated by Django 6.0.6 on 2026-06-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_artist_name_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name_fa',
        ),
        migrations.AddField(
            model_name='music',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, help_text='شماره ترک در آلبوم', null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='year',
            field=models.CharField(blank=True, help_text='سال انتشار آهنگ', max_length=10, null=True),
        ),
    ]
