# Generated by Django 6.0.6 on 2026-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_remove_artist_name_fa_music_track_number_music_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='zip_file',
            field=models.FileField(blank=True, help_text='فایل زیپ کامل آلبوم', null=True, upload_to='album_zips/'),
        ),
    ]
