# Generated by Django 6.0.6 on 2026-06-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_album_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='zip_file',
            field=models.FileField(blank=True, help_text='فایل زیپ کامل آلبوم', null=True, upload_to='albums_zip/'),
        ),
    ]
