# Generated by Django 6.0.6 on 2026-06-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_album_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='search_aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='search_aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='search_aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='music',
            name='search_aliases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='albums_zip/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
