# Generated by Django 6.0.6 on 2026-06-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_album_search_aliases_artist_search_aliases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='search_aliases',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='search_aliases',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='search_aliases',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='is_vip',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='search_aliases',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
