# Generated by Django 6.0.6 on 2026-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_album_search_aliases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='musics', to='music.artist'),
        ),
    ]
