# Generated by Django 6.0.6 on 2026-06-25 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_music_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music.music'),
        ),
    ]
