# Generated by Django 6.0.6 on 2026-07-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_alter_like_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('music', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
            ],
        ),
    ]
