# Generated by Django 6.0.6 on 2026-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_telegrambotstate_telegramfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
