# Generated by Django 6.0.6 on 2026-07-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_music_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
