# Generated by Django 6.0.6 on 2026-07-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_music_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='zip_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
