# Generated by Django 6.0.6 on 2026-07-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_telegramimportedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='zip_file',
        ),
    ]
