# Generated by Django 6.0.6 on 2026-07-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_remove_album_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='zip_url',
        ),
    ]
