# Generated by Django 6.0.5 on 2026-06-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
